// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreatePostsInBatch implements pgx.CopyFromSource.
type iteratorForCreatePostsInBatch struct {
	rows                 []CreatePostsInBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePostsInBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePostsInBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForCreatePostsInBatch) Err() error {
	return nil
}

func (q *Queries) CreatePostsInBatch(ctx context.Context, arg []CreatePostsInBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"posts"}, []string{"user_id", "content"}, &iteratorForCreatePostsInBatch{rows: arg})
}
